import "./globals.js";

export const Array: ArrayConstructor;
export const ArrayBuffer: ArrayBufferConstructor;
export const BigInt: BigIntConstructor;
export const Boolean: BooleanConstructor;
export const DataView: DataViewConstructor;
export const Date: DateConstructor;
export const Error: ErrorConstructor;
export const Float32Array: Float32ArrayConstructor;
export const Float64Array: Float64ArrayConstructor;
export const Infinity: number;
export const Int8Array: Int8ArrayConstructor;
export const Int16Array: Int16ArrayConstructor;
export const Int32Array: Int32ArrayConstructor;
export const JSON: JSON;
export const Map: MapConstructor;
export const Math: Math;
export const NaN: number;
export const Number: NumberConstructor;
export const Object: ObjectConstructor;
export const RangeError: ErrorConstructor;
export const RegExp: RegExpConstructor;
export const Set: SetConstructor;
export const String: StringConstructor;
export const TextEncoder: typeof globalThis.TextEncoder;
export const Uint8Array: Uint8ArrayConstructor;
export const Uint8ClampedArray: Uint8ClampedArrayConstructor;
export const Uint16Array: Uint16ArrayConstructor;
export const Uint32Array: Uint32ArrayConstructor;
export const WeakMap: WeakMapConstructor;
export const WeakSet: WeakSetConstructor;
export const console: Console;
export const decodeURI: typeof globalThis.decodeURI;
export const decodeURIComponent: typeof globalThis.decodeURIComponent;
export const encodeURI: typeof globalThis.encodeURI;
export const encodeURIComponent: typeof globalThis.encodeURIComponent;
export const isFinite: typeof globalThis.isFinite;
export const isNaN: typeof globalThis.isNaN;
export const parseFloat: typeof globalThis.parseFloat;
export const parseInt: typeof globalThis.parseInt;

export type ReadonlyMap<K, V> = globalThis.ReadonlyMap<K, V>;
export type ReadonlySet<T> = globalThis.ReadonlySet<T>;
