// Generated by tsbindgen - Architecture
// Namespace: Tsonic.JSRuntime
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './index/internal/index.js';

// Primitive type aliases for flattened exports
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Namespace imports for flattened exports
import * as System_Internal from "@tsonic/dotnet/System.js";

// Cross-namespace type imports for constraints
import type { IEnumerable as IEnumerable__System_Collections_Generic, IEnumerator, KeyValuePair, List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.js';
import type { Action, Boolean as ClrBoolean, Byte, Comparison, Double, Func, Int16, Int32, Int64, Nullable, Object as ClrObject, SByte, Single, String as ClrString, UInt16, UInt32, ValueTuple, Void } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { ArrayBuffer as ArrayBuffer } from './index/internal/index.js';
export { console$instance as console } from './index/internal/index.js';
export { Date as Date } from './index/internal/index.js';
export { Float32Array as Float32Array } from './index/internal/index.js';
export { Float64Array as Float64Array } from './index/internal/index.js';
export { Globals$instance as Globals } from './index/internal/index.js';
export { Int16Array as Int16Array } from './index/internal/index.js';
export { Int32Array as Int32Array } from './index/internal/index.js';
export { Int8Array as Int8Array } from './index/internal/index.js';
export { JSArray_1 as JSArray } from './index/internal/index.js';
export { JSON$instance as JSON } from './index/internal/index.js';
export { Map_2 as Map } from './index/internal/index.js';
export { Math$instance as Math } from './index/internal/index.js';
export { Number$instance as Number } from './index/internal/index.js';
export { RegExp as RegExp } from './index/internal/index.js';
export { RegExpMatchResult as RegExpMatchResult } from './index/internal/index.js';
export { Set_1 as Set } from './index/internal/index.js';
export { String$instance as String } from './index/internal/index.js';
export { Timers$instance as Timers } from './index/internal/index.js';
export { Uint16Array as Uint16Array } from './index/internal/index.js';
export { Uint32Array as Uint32Array } from './index/internal/index.js';
export { Uint8Array as Uint8Array } from './index/internal/index.js';
export { Uint8ClampedArray as Uint8ClampedArray } from './index/internal/index.js';
export { WeakMap_2 as WeakMap } from './index/internal/index.js';
export { WeakSet_1 as WeakSet } from './index/internal/index.js';

// Flattened exports from static classes
// From Tsonic.JSRuntime.Globals
export declare function boolean(value: unknown): boolean;
export declare function decodeURI(uri: string): string;
export declare function decodeURIComponent(component: string): string;
export declare function encodeURI(uri: string): string;
export declare function encodeURIComponent(component: string): string;
export declare function isFinite(value: double): boolean;
export declare function isNaN(value: double): boolean;
export declare function number(value: unknown): double;
export declare function parseFloat(str: string): double;
export declare function parseInt(str: string, radix?: Nullable<System_Internal.Int32>): Nullable<System_Internal.Int64>;
export declare function string(value: unknown): string;
