// Generated by tsbindgen - Extension Method Buckets
// This file contains bucket interfaces for C# extension methods.
// Buckets are scoped by declaring namespace (C# using semantics).
// For each namespace with extension methods, this file exports an ExtensionMethods_<Namespace> helper.

// Import namespace modules for cross-namespace type references
import * as System from "@tsonic/dotnet/System/internal/index.js";
import * as System_Collections_Generic from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";

// Import primitive type aliases
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import sticky extension scope helper
import type { Rewrap } from '@tsonic/core/lang.js';

// Import CLR type aliases for generic type arguments
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";

// Import unsafe type markers
import type { ptr } from '@tsonic/core/types.js';

export interface __Ext_Tsonic_JSRuntime_String {
  toUpperCase(): Rewrap<this, string>;
  toLowerCase(): Rewrap<this, string>;
  trim(): Rewrap<this, string>;
  trimStart(): Rewrap<this, string>;
  trimEnd(): Rewrap<this, string>;
  substring(start: int, end?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string>;
  slice(start: int, end?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string>;
  indexOf(searchString: string, position?: int): Rewrap<this, int>;
  lastIndexOf(searchString: string, position?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, int>;
  startsWith(searchString: string): Rewrap<this, boolean>;
  endsWith(searchString: string): Rewrap<this, boolean>;
  includes(searchString: string): Rewrap<this, boolean>;
  replace(search: string, replacement: string): Rewrap<this, string>;
  repeat(count: int): Rewrap<this, string>;
  padStart(targetLength: int, padString?: string): Rewrap<this, string>;
  padEnd(targetLength: int, padString?: string): Rewrap<this, string>;
  charAt(index: int): Rewrap<this, string>;
  charCodeAt(index: int): Rewrap<this, int>;
  split(separator: string, limit?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, System_Collections_Generic.List_1<System_Internal.String>>;
  length(): Rewrap<this, int>;
  at(index: int): Rewrap<this, string>;
  codePointAt(index: int): Rewrap<this, int>;
  concat(...strings: string[]): Rewrap<this, string>;
  localeCompare(compareString: string): Rewrap<this, int>;
  match(pattern: string): Rewrap<this, System_Collections_Generic.List_1<System_Internal.String> | undefined>;
  matchAll(pattern: string): Rewrap<this, System_Collections_Generic.List_1<System_Collections_Generic.List_1<System_Internal.String>>>;
  search(pattern: string): Rewrap<this, int>;
  replaceAll(search: string, replacement: string): Rewrap<this, string>;
  normalize(form?: string): Rewrap<this, string>;
  substr(start: int, length?: System.Nullable_1<System_Internal.Int32>): Rewrap<this, string>;
  toLocaleLowerCase(): Rewrap<this, string>;
  toLocaleUpperCase(): Rewrap<this, string>;
  toString(): Rewrap<this, string>;
  valueOf(): Rewrap<this, string>;
  isWellFormed(): Rewrap<this, boolean>;
  toWellFormed(): Rewrap<this, string>;
  trimLeft(): Rewrap<this, string>;
  trimRight(): Rewrap<this, string>;
}

// Internal helper types for sticky extension scopes
type __TsonicExtMapOf<T> = T extends { __tsonic_ext?: infer M } ? M : {};
type __TsonicMergeExtMaps<A, B> = A & B;
type __TsonicWithExt<TShape, K extends string, TApplier> = { __tsonic_ext?: __TsonicMergeExtMaps<__TsonicExtMapOf<TShape>, { [P in K]: TApplier }> };

// Generic helper type for extension methods in namespace: Tsonic.JSRuntime
type __TsonicExtSurface_Tsonic_JSRuntime<TShape> =
  (
    (TShape extends string ? __Ext_Tsonic_JSRuntime_String : {})
  );

interface __TsonicExtApplier_Tsonic_JSRuntime {
  __tsonic_shape: unknown;
  __tsonic_type: __TsonicExtSurface_Tsonic_JSRuntime<this["__tsonic_shape"]>;
}

export type ExtensionMethods_Tsonic_JSRuntime<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & __TsonicWithExt<TShape, "Tsonic.JSRuntime", __TsonicExtApplier_Tsonic_JSRuntime> & __TsonicExtSurface_Tsonic_JSRuntime<TShape>;

