// Generated by tsbindgen - Extension Method Buckets
// This file contains bucket interfaces for C# extension methods.
// Buckets are scoped by declaring namespace (C# using semantics).
// For each namespace with extension methods, this file exports an ExtensionMethods_<Namespace> helper.

// Import namespace modules for cross-namespace type references
import * as System from "@tsonic/dotnet/System/internal/index.js";
import * as System_Collections_Generic from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";

// Import primitive type aliases
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import CLR type aliases for generic type arguments
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";

// Import unsafe type markers
import type { ptr } from '@tsonic/core/types.js';

export interface __Ext_Tsonic_JSRuntime_String {
  toUpperCase(): ExtensionMethods_Tsonic_JSRuntime<string>;
  toLowerCase(): ExtensionMethods_Tsonic_JSRuntime<string>;
  trim(): ExtensionMethods_Tsonic_JSRuntime<string>;
  trimStart(): ExtensionMethods_Tsonic_JSRuntime<string>;
  trimEnd(): ExtensionMethods_Tsonic_JSRuntime<string>;
  substring(start: int, end?: System.Nullable_1<System_Internal.Int32>): ExtensionMethods_Tsonic_JSRuntime<string>;
  slice(start: int, end?: System.Nullable_1<System_Internal.Int32>): ExtensionMethods_Tsonic_JSRuntime<string>;
  indexOf(searchString: string, position?: int): ExtensionMethods_Tsonic_JSRuntime<int>;
  lastIndexOf(searchString: string, position?: System.Nullable_1<System_Internal.Int32>): ExtensionMethods_Tsonic_JSRuntime<int>;
  startsWith(searchString: string): ExtensionMethods_Tsonic_JSRuntime<boolean>;
  endsWith(searchString: string): ExtensionMethods_Tsonic_JSRuntime<boolean>;
  includes(searchString: string): ExtensionMethods_Tsonic_JSRuntime<boolean>;
  replace(search: string, replacement: string): ExtensionMethods_Tsonic_JSRuntime<string>;
  repeat(count: int): ExtensionMethods_Tsonic_JSRuntime<string>;
  padStart(targetLength: int, padString?: string): ExtensionMethods_Tsonic_JSRuntime<string>;
  padEnd(targetLength: int, padString?: string): ExtensionMethods_Tsonic_JSRuntime<string>;
  charAt(index: int): ExtensionMethods_Tsonic_JSRuntime<string>;
  charCodeAt(index: int): ExtensionMethods_Tsonic_JSRuntime<int>;
  split(separator: string, limit?: System.Nullable_1<System_Internal.Int32>): ExtensionMethods_Tsonic_JSRuntime<System_Collections_Generic.List_1<System_Internal.String>>;
  length(): ExtensionMethods_Tsonic_JSRuntime<int>;
  at(index: int): ExtensionMethods_Tsonic_JSRuntime<string>;
  codePointAt(index: int): ExtensionMethods_Tsonic_JSRuntime<int>;
  concat(...strings: string[]): ExtensionMethods_Tsonic_JSRuntime<string>;
  localeCompare(compareString: string): ExtensionMethods_Tsonic_JSRuntime<int>;
  match(pattern: string): ExtensionMethods_Tsonic_JSRuntime<System_Collections_Generic.List_1<System_Internal.String> | undefined>;
  matchAll(pattern: string): ExtensionMethods_Tsonic_JSRuntime<System_Collections_Generic.List_1<System_Collections_Generic.List_1<System_Internal.String>>>;
  search(pattern: string): ExtensionMethods_Tsonic_JSRuntime<int>;
  replaceAll(search: string, replacement: string): ExtensionMethods_Tsonic_JSRuntime<string>;
  normalize(form?: string): ExtensionMethods_Tsonic_JSRuntime<string>;
  substr(start: int, length?: System.Nullable_1<System_Internal.Int32>): ExtensionMethods_Tsonic_JSRuntime<string>;
  toLocaleLowerCase(): ExtensionMethods_Tsonic_JSRuntime<string>;
  toLocaleUpperCase(): ExtensionMethods_Tsonic_JSRuntime<string>;
  toString(): ExtensionMethods_Tsonic_JSRuntime<string>;
  valueOf(): ExtensionMethods_Tsonic_JSRuntime<string>;
  isWellFormed(): ExtensionMethods_Tsonic_JSRuntime<boolean>;
  toWellFormed(): ExtensionMethods_Tsonic_JSRuntime<string>;
  trimLeft(): ExtensionMethods_Tsonic_JSRuntime<string>;
  trimRight(): ExtensionMethods_Tsonic_JSRuntime<string>;
}

// Generic helper type for extension methods in namespace: Tsonic.JSRuntime
export type ExtensionMethods_Tsonic_JSRuntime<TShape> =
  TShape extends null | undefined ? TShape
  : TShape extends void ? void
  : TShape & (
    (TShape extends string ? __Ext_Tsonic_JSRuntime_String : {})
  );

